[2024-03-04 20:03:02,574: INFO: main: hello world]
[2024-03-07 09:59:01,673: INFO: main: hello world]
[2024-03-07 09:59:37,709: INFO: main: hello world]
[2024-03-07 12:55:17,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:55:17,930: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:55:17,932: INFO: common: created directory at: artifacts]
[2024-03-07 12:55:57,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:55:57,321: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:55:57,325: INFO: common: created directory at: artifacts]
[2024-03-07 12:55:57,640: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 12:57:30,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:57:30,633: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:57:30,635: INFO: common: created directory at: artifacts]
[2024-03-07 12:57:30,637: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 12:58:14,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:58:14,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:58:14,496: INFO: common: created directory at: artifacts]
[2024-03-07 12:58:14,497: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 13:03:56,167: INFO: 2813064552: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-07 13:19:04,131: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 13:19:04,133: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 13:19:04,133: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 13:19:04,133: INFO: common: created directory at: artifacts]
[2024-03-07 13:19:04,134: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 13:27:55,005: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-07 13:28:09,088: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-07 23:52:31,872: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 23:52:31,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 23:52:31,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 23:52:31,875: INFO: common: created directory at: artifacts]
[2024-03-07 23:52:31,876: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 23:52:57,217: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 23:52:57,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 23:52:57,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 23:52:57,219: INFO: common: created directory at: artifacts]
[2024-03-07 23:52:57,220: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 00:00:37,478: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 00:00:57,886: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-12 02:02:39,909: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:02:40,012: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:04:06,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:04:06,335: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:04:06,336: INFO: common: created directory at: artifacts]
[2024-03-12 02:04:06,337: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:04:52,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:04:52,914: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:04:52,915: INFO: common: created directory at: artifacts]
[2024-03-12 02:04:52,916: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:07:20,520: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:07:20,524: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:07:20,526: INFO: common: created directory at: artifacts]
[2024-03-12 02:07:20,528: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:07:44,008: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:07:44,515: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:29:28,182: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-12 02:29:28,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:29:28,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:29:28,276: INFO: common: created directory at: artifacts]
[2024-03-12 02:29:28,276: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-12 02:35:37,825: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-12 02:36:02,393: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-12 02:36:02,394: INFO: main: ******************]
[2024-03-12 02:36:02,394: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-12 02:36:02,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:36:02,399: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:36:02,400: INFO: common: created directory at: artifacts]
[2024-03-12 02:36:02,400: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:36:03,165: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:36:04,431: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:36:04,701: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 02:59:07,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 02:59:09,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 02:59:09,268: INFO: common: created directory at: artifacts]
[2024-03-14 02:59:09,269: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:01:40,017: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:01:40,022: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:01:40,024: INFO: common: created directory at: artifacts]
[2024-03-14 03:01:40,026: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:02:49,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:02:49,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:02:49,115: INFO: common: created directory at: artifacts]
[2024-03-14 03:02:49,117: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:04:18,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:04:18,426: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:04:18,428: INFO: common: created directory at: artifacts]
[2024-03-14 03:04:18,430: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:05:14,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:05:15,356: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:05:15,358: INFO: common: created directory at: artifacts]
[2024-03-14 03:05:15,360: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:05:59,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:05:59,590: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:05:59,594: INFO: common: created directory at: artifacts]
[2024-03-14 03:05:59,595: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:09:03,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:09:03,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:09:03,954: INFO: common: created directory at: artifacts]
[2024-03-14 03:09:03,956: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:11:39,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:11:39,347: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:11:39,349: INFO: common: created directory at: artifacts]
[2024-03-14 03:11:39,351: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:15:53,591: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:15:53,596: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:15:53,599: INFO: common: created directory at: artifacts]
[2024-03-14 03:15:53,601: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:17:08,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:17:08,184: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:17:08,186: INFO: common: created directory at: artifacts]
[2024-03-14 03:17:08,187: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:18:33,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:18:33,143: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:18:33,145: INFO: common: created directory at: artifacts]
[2024-03-14 03:18:33,148: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:48:24,146: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-14 03:48:24,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:48:24,268: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:48:24,269: INFO: common: created directory at: artifacts]
[2024-03-14 03:48:24,269: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 03:55:08,650: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 03:55:26,858: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-14 03:55:26,858: INFO: main: ******************]
[2024-03-14 03:55:26,858: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 03:55:26,862: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:55:26,864: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:55:26,865: INFO: common: created directory at: artifacts]
[2024-03-14 03:55:26,865: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 03:55:27,583: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 03:55:28,639: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 03:55:29,105: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 03:55:29,105: INFO: main: ******************]
[2024-03-14 03:55:29,105: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 03:55:29,109: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:55:29,111: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:55:29,111: INFO: common: created directory at: artifacts]
[2024-03-14 03:55:29,111: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:55:29,556: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 04:07:35,686: INFO: main: ******************]
[2024-03-14 04:07:35,687: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:07:35,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:07:35,692: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:07:35,693: INFO: common: created directory at: artifacts]
[2024-03-14 04:07:35,693: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:07:36,288: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:07:36,881: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:07:37,238: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:07:37,238: INFO: main: ******************]
[2024-03-14 04:07:37,238: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:07:37,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:07:37,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:07:37,244: INFO: common: created directory at: artifacts]
[2024-03-14 04:07:37,245: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:07:37,673: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 04:08:57,810: INFO: main: ******************]
[2024-03-14 04:08:57,811: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:08:57,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:08:57,814: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:08:57,814: INFO: common: created directory at: artifacts]
[2024-03-14 04:08:57,815: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:08:58,323: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:08:58,905: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:08:59,145: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:08:59,145: INFO: main: ******************]
[2024-03-14 04:08:59,145: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:08:59,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:08:59,150: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:08:59,151: INFO: common: created directory at: artifacts]
[2024-03-14 04:08:59,151: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:08:59,487: ERROR: main: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 04:11:03,686: INFO: main: ******************]
[2024-03-14 04:11:03,686: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:11:03,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:11:03,690: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:11:03,691: INFO: common: created directory at: artifacts]
[2024-03-14 04:11:03,691: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:11:04,180: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:11:04,806: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:11:05,047: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:11:05,047: INFO: main: ******************]
[2024-03-14 04:11:05,047: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:11:05,050: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:11:05,053: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:11:05,054: INFO: common: created directory at: artifacts]
[2024-03-14 04:11:05,159: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:11:05,465: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-03-14 04:16:57,807: INFO: main: ******************]
[2024-03-14 04:16:57,807: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:16:57,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:16:57,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:16:57,812: INFO: common: created directory at: artifacts]
[2024-03-14 04:16:57,812: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:16:58,217: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:16:58,636: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:16:58,829: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:16:58,830: INFO: main: ******************]
[2024-03-14 04:16:58,830: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:16:58,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:16:58,835: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:16:58,835: INFO: common: created directory at: artifacts]
[2024-03-14 04:16:58,836: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:16:59,138: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "d:/Courses/ML/MachineLearning/ML_Projects/Computer_Vision/Kidney_Disease_Classification_Project/main.py", line 34, in <module>
    obj.main()
  File "d:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "d:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-03-14 04:31:44,420: INFO: main: ******************]
[2024-03-14 04:31:44,420: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:31:44,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:31:44,428: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:31:44,428: INFO: common: created directory at: artifacts]
[2024-03-14 04:31:44,428: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:31:44,988: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:31:45,561: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:31:45,929: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:31:45,929: INFO: main: ******************]
[2024-03-14 04:31:45,929: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:31:45,933: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:31:45,935: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:31:45,935: INFO: common: created directory at: artifacts]
[2024-03-14 04:31:45,936: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:31:46,387: ERROR: main: Asked to retrieve element 0, but the Sequence has length 0]
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 103, in __getitem__
    raise ValueError(
ValueError: Asked to retrieve element 0, but the Sequence has length 0
[2024-03-14 04:35:28,177: INFO: main: ******************]
[2024-03-14 04:35:28,177: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:35:28,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:35:28,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:35:28,184: INFO: common: created directory at: artifacts]
[2024-03-14 04:35:28,184: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:35:28,775: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:35:29,426: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:35:29,677: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:35:29,677: INFO: main: ******************]
[2024-03-14 04:35:29,678: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:35:29,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:35:29,683: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:35:29,684: INFO: common: created directory at: artifacts]
[2024-03-14 04:35:29,684: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:35:30,140: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-03-14 04:36:10,490: INFO: main: ******************]
[2024-03-14 04:36:10,490: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:36:10,493: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:36:10,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:36:10,494: INFO: common: created directory at: artifacts]
[2024-03-14 04:36:10,495: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:36:11,004: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:36:11,638: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:36:11,883: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:36:11,884: INFO: main: ******************]
[2024-03-14 04:36:11,884: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:36:11,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:36:11,890: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:36:11,890: INFO: common: created directory at: artifacts]
[2024-03-14 04:36:11,891: INFO: common: created directory at: artifacts\training]
[2024-03-14 15:05:28,323: INFO: main: ******************]
[2024-03-14 15:05:28,323: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 15:05:28,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:05:28,329: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:05:28,330: INFO: common: created directory at: artifacts]
[2024-03-14 15:05:28,330: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 15:05:28,809: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 15:05:29,211: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 15:05:29,508: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 15:05:29,508: INFO: main: ******************]
[2024-03-14 15:05:29,508: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 15:05:29,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:05:29,512: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:05:29,513: INFO: common: created directory at: artifacts]
[2024-03-14 15:05:29,513: INFO: common: created directory at: artifacts\training]
[2024-03-15 19:42:47,268: INFO: main: >>>>>> stage Training completed <<<<<<]
[2024-04-23 11:05:35,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-23 11:05:35,799: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-23 11:05:35,838: INFO: common: created directory at: artifacts]
[2024-04-23 11:07:56,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-23 11:07:56,227: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-23 11:07:56,228: INFO: common: created directory at: artifacts]
[2024-04-23 11:09:42,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-23 11:09:42,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-23 11:09:42,164: INFO: common: created directory at: artifacts]
[2024-04-23 11:16:04,184: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-23 11:16:05,497: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmphgxcue_w\model\data\model\assets]
[2024-04-23 11:21:56,794: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-23 11:30:49,750: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-23 11:41:46,634: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-23 18:32:21,486: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=5, read=1, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:01:06,538: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=5, read=0, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:39:43,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 08:39:43,338: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 08:39:43,341: INFO: common: created directory at: artifacts]
[2024-04-24 08:46:37,715: INFO: common: json file saved at: scores.json]
[2024-04-24 08:46:43,474: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-24 08:46:44,888: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmpnfw1cy22\model\data\model\assets]
[2024-04-24 08:54:10,493: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/3efc62a5f24b41fd9ee051c12e93226a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:54:14,512: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=4, read=4, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000220BA2C6130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/3efc62a5f24b41fd9ee051c12e93226a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:54:23,054: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=3, read=4, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000220BA2A88B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/3efc62a5f24b41fd9ee051c12e93226a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 09:35:28,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 09:35:28,380: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 09:35:28,381: INFO: common: created directory at: artifacts]
[2024-04-24 09:38:53,064: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 09:38:53,083: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 09:38:53,088: INFO: common: created directory at: artifacts]
[2024-04-24 09:46:24,288: INFO: common: json file saved at: scores.json]
[2024-04-24 09:46:35,109: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-24 09:46:41,026: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmpnuwsfyxk\model\data\model\assets]
[2024-04-24 10:05:34,799: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/2ad20db6c2f04a3d9f29125c503d41b1/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 10:06:10,986: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/2ad20db6c2f04a3d9f29125c503d41b1/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 10:07:58,984: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/2ad20db6c2f04a3d9f29125c503d41b1/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 10:11:18,157: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-24 10:11:18,158: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-24 10:11:21,897: INFO: main: ******************]
[2024-04-24 10:11:21,897: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-24 10:11:21,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 10:11:21,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 10:11:21,904: INFO: common: created directory at: artifacts]
[2024-04-24 10:11:21,904: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-24 10:11:22,621: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-24 10:11:23,694: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-24 10:11:24,287: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-04-24 10:11:24,287: INFO: main: ******************]
[2024-04-24 10:11:24,287: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-24 10:11:24,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 10:11:24,296: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 10:11:24,296: INFO: common: created directory at: artifacts]
[2024-04-24 10:11:24,297: INFO: common: created directory at: artifacts\training]
