[2024-03-04 20:03:02,574: INFO: main: hello world]
[2024-03-07 09:59:01,673: INFO: main: hello world]
[2024-03-07 09:59:37,709: INFO: main: hello world]
[2024-03-07 12:55:17,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:55:17,930: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:55:17,932: INFO: common: created directory at: artifacts]
[2024-03-07 12:55:57,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:55:57,321: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:55:57,325: INFO: common: created directory at: artifacts]
[2024-03-07 12:55:57,640: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 12:57:30,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:57:30,633: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:57:30,635: INFO: common: created directory at: artifacts]
[2024-03-07 12:57:30,637: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 12:58:14,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:58:14,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:58:14,496: INFO: common: created directory at: artifacts]
[2024-03-07 12:58:14,497: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 13:03:56,167: INFO: 2813064552: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-07 13:19:04,131: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 13:19:04,133: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 13:19:04,133: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 13:19:04,133: INFO: common: created directory at: artifacts]
[2024-03-07 13:19:04,134: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 13:27:55,005: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-07 13:28:09,088: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-07 23:52:31,872: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 23:52:31,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 23:52:31,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 23:52:31,875: INFO: common: created directory at: artifacts]
[2024-03-07 23:52:31,876: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 23:52:57,217: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 23:52:57,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 23:52:57,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 23:52:57,219: INFO: common: created directory at: artifacts]
[2024-03-07 23:52:57,220: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 00:00:37,478: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 00:00:57,886: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-12 02:02:39,909: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:02:40,012: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:04:06,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:04:06,335: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:04:06,336: INFO: common: created directory at: artifacts]
[2024-03-12 02:04:06,337: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:04:52,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:04:52,914: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:04:52,915: INFO: common: created directory at: artifacts]
[2024-03-12 02:04:52,916: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:07:20,520: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:07:20,524: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:07:20,526: INFO: common: created directory at: artifacts]
[2024-03-12 02:07:20,528: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:07:44,008: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:07:44,515: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:29:28,182: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-12 02:29:28,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:29:28,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:29:28,276: INFO: common: created directory at: artifacts]
[2024-03-12 02:29:28,276: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-12 02:35:37,825: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-12 02:36:02,393: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-12 02:36:02,394: INFO: main: ******************]
[2024-03-12 02:36:02,394: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-12 02:36:02,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 02:36:02,399: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 02:36:02,400: INFO: common: created directory at: artifacts]
[2024-03-12 02:36:02,400: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 02:36:03,165: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:36:04,431: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 02:36:04,701: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 02:59:07,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 02:59:09,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 02:59:09,268: INFO: common: created directory at: artifacts]
[2024-03-14 02:59:09,269: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:01:40,017: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:01:40,022: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:01:40,024: INFO: common: created directory at: artifacts]
[2024-03-14 03:01:40,026: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:02:49,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:02:49,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:02:49,115: INFO: common: created directory at: artifacts]
[2024-03-14 03:02:49,117: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:04:18,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:04:18,426: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:04:18,428: INFO: common: created directory at: artifacts]
[2024-03-14 03:04:18,430: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:05:14,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:05:15,356: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:05:15,358: INFO: common: created directory at: artifacts]
[2024-03-14 03:05:15,360: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:05:59,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:05:59,590: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:05:59,594: INFO: common: created directory at: artifacts]
[2024-03-14 03:05:59,595: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:09:03,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:09:03,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:09:03,954: INFO: common: created directory at: artifacts]
[2024-03-14 03:09:03,956: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:11:39,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:11:39,347: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:11:39,349: INFO: common: created directory at: artifacts]
[2024-03-14 03:11:39,351: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:15:53,591: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:15:53,596: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:15:53,599: INFO: common: created directory at: artifacts]
[2024-03-14 03:15:53,601: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:17:08,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:17:08,184: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:17:08,186: INFO: common: created directory at: artifacts]
[2024-03-14 03:17:08,187: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:18:33,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:18:33,143: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:18:33,145: INFO: common: created directory at: artifacts]
[2024-03-14 03:18:33,148: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:48:24,146: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-03-14 03:48:24,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:48:24,268: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:48:24,269: INFO: common: created directory at: artifacts]
[2024-03-14 03:48:24,269: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 03:55:08,650: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 03:55:26,858: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-03-14 03:55:26,858: INFO: main: ******************]
[2024-03-14 03:55:26,858: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 03:55:26,862: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:55:26,864: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:55:26,865: INFO: common: created directory at: artifacts]
[2024-03-14 03:55:26,865: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 03:55:27,583: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 03:55:28,639: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 03:55:29,105: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 03:55:29,105: INFO: main: ******************]
[2024-03-14 03:55:29,105: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 03:55:29,109: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:55:29,111: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:55:29,111: INFO: common: created directory at: artifacts]
[2024-03-14 03:55:29,111: INFO: common: created directory at: artifacts\training]
[2024-03-14 03:55:29,556: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 04:07:35,686: INFO: main: ******************]
[2024-03-14 04:07:35,687: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:07:35,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:07:35,692: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:07:35,693: INFO: common: created directory at: artifacts]
[2024-03-14 04:07:35,693: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:07:36,288: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:07:36,881: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:07:37,238: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:07:37,238: INFO: main: ******************]
[2024-03-14 04:07:37,238: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:07:37,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:07:37,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:07:37,244: INFO: common: created directory at: artifacts]
[2024-03-14 04:07:37,245: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:07:37,673: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 04:08:57,810: INFO: main: ******************]
[2024-03-14 04:08:57,811: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:08:57,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:08:57,814: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:08:57,814: INFO: common: created directory at: artifacts]
[2024-03-14 04:08:57,815: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:08:58,323: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:08:58,905: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:08:59,145: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:08:59,145: INFO: main: ******************]
[2024-03-14 04:08:59,145: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:08:59,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:08:59,150: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:08:59,151: INFO: common: created directory at: artifacts]
[2024-03-14 04:08:59,151: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:08:59,487: ERROR: main: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 04:11:03,686: INFO: main: ******************]
[2024-03-14 04:11:03,686: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:11:03,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:11:03,690: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:11:03,691: INFO: common: created directory at: artifacts]
[2024-03-14 04:11:03,691: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:11:04,180: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:11:04,806: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:11:05,047: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:11:05,047: INFO: main: ******************]
[2024-03-14 04:11:05,047: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:11:05,050: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:11:05,053: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:11:05,054: INFO: common: created directory at: artifacts]
[2024-03-14 04:11:05,159: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:11:05,465: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-03-14 04:16:57,807: INFO: main: ******************]
[2024-03-14 04:16:57,807: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:16:57,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:16:57,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:16:57,812: INFO: common: created directory at: artifacts]
[2024-03-14 04:16:57,812: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:16:58,217: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:16:58,636: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:16:58,829: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:16:58,830: INFO: main: ******************]
[2024-03-14 04:16:58,830: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:16:58,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:16:58,835: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:16:58,835: INFO: common: created directory at: artifacts]
[2024-03-14 04:16:58,836: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:16:59,138: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "d:/Courses/ML/MachineLearning/ML_Projects/Computer_Vision/Kidney_Disease_Classification_Project/main.py", line 34, in <module>
    obj.main()
  File "d:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "d:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-03-14 04:31:44,420: INFO: main: ******************]
[2024-03-14 04:31:44,420: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:31:44,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:31:44,428: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:31:44,428: INFO: common: created directory at: artifacts]
[2024-03-14 04:31:44,428: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:31:44,988: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:31:45,561: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:31:45,929: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:31:45,929: INFO: main: ******************]
[2024-03-14 04:31:45,929: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:31:45,933: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:31:45,935: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:31:45,935: INFO: common: created directory at: artifacts]
[2024-03-14 04:31:45,936: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:31:46,387: ERROR: main: Asked to retrieve element 0, but the Sequence has length 0]
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 103, in __getitem__
    raise ValueError(
ValueError: Asked to retrieve element 0, but the Sequence has length 0
[2024-03-14 04:35:28,177: INFO: main: ******************]
[2024-03-14 04:35:28,177: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:35:28,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:35:28,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:35:28,184: INFO: common: created directory at: artifacts]
[2024-03-14 04:35:28,184: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:35:28,775: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:35:29,426: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:35:29,677: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:35:29,677: INFO: main: ******************]
[2024-03-14 04:35:29,678: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:35:29,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:35:29,683: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:35:29,684: INFO: common: created directory at: artifacts]
[2024-03-14 04:35:29,684: INFO: common: created directory at: artifacts\training]
[2024-03-14 04:35:30,140: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-03-14 04:36:10,490: INFO: main: ******************]
[2024-03-14 04:36:10,490: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 04:36:10,493: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:36:10,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:36:10,494: INFO: common: created directory at: artifacts]
[2024-03-14 04:36:10,495: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 04:36:11,004: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:36:11,638: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 04:36:11,883: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 04:36:11,884: INFO: main: ******************]
[2024-03-14 04:36:11,884: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 04:36:11,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 04:36:11,890: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 04:36:11,890: INFO: common: created directory at: artifacts]
[2024-03-14 04:36:11,891: INFO: common: created directory at: artifacts\training]
[2024-03-14 15:05:28,323: INFO: main: ******************]
[2024-03-14 15:05:28,323: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 15:05:28,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:05:28,329: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:05:28,330: INFO: common: created directory at: artifacts]
[2024-03-14 15:05:28,330: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 15:05:28,809: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 15:05:29,211: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 15:05:29,508: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-03-14 15:05:29,508: INFO: main: ******************]
[2024-03-14 15:05:29,508: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 15:05:29,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:05:29,512: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:05:29,513: INFO: common: created directory at: artifacts]
[2024-03-14 15:05:29,513: INFO: common: created directory at: artifacts\training]
[2024-03-15 19:42:47,268: INFO: main: >>>>>> stage Training completed <<<<<<]
[2024-04-23 11:05:35,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-23 11:05:35,799: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-23 11:05:35,838: INFO: common: created directory at: artifacts]
[2024-04-23 11:07:56,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-23 11:07:56,227: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-23 11:07:56,228: INFO: common: created directory at: artifacts]
[2024-04-23 11:09:42,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-23 11:09:42,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-23 11:09:42,164: INFO: common: created directory at: artifacts]
[2024-04-23 11:16:04,184: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-23 11:16:05,497: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmphgxcue_w\model\data\model\assets]
[2024-04-23 11:21:56,794: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-23 11:30:49,750: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-23 11:41:46,634: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-23 18:32:21,486: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=5, read=1, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:01:06,538: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=5, read=0, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/c9db72b508a74768897051dd695bfdbb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:39:43,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 08:39:43,338: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 08:39:43,341: INFO: common: created directory at: artifacts]
[2024-04-24 08:46:37,715: INFO: common: json file saved at: scores.json]
[2024-04-24 08:46:43,474: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-24 08:46:44,888: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmpnfw1cy22\model\data\model\assets]
[2024-04-24 08:54:10,493: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/3efc62a5f24b41fd9ee051c12e93226a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:54:14,512: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=4, read=4, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000220BA2C6130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/3efc62a5f24b41fd9ee051c12e93226a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 08:54:23,054: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=3, read=4, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000220BA2A88B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/3efc62a5f24b41fd9ee051c12e93226a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 09:35:28,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 09:35:28,380: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 09:35:28,381: INFO: common: created directory at: artifacts]
[2024-04-24 09:38:53,064: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 09:38:53,083: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 09:38:53,088: INFO: common: created directory at: artifacts]
[2024-04-24 09:46:24,288: INFO: common: json file saved at: scores.json]
[2024-04-24 09:46:35,109: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-24 09:46:41,026: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmpnuwsfyxk\model\data\model\assets]
[2024-04-24 10:05:34,799: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/2ad20db6c2f04a3d9f29125c503d41b1/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 10:06:10,986: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/2ad20db6c2f04a3d9f29125c503d41b1/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 10:07:58,984: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /KhaledAshrafM/Kidney_Disease_Classification_Project.mlflow/api/2.0/mlflow-artifacts/artifacts/22d4db5e293d4e81b54e2957e51ba859/2ad20db6c2f04a3d9f29125c503d41b1/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-04-24 10:11:18,157: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-24 10:11:18,158: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-24 10:11:21,897: INFO: main: ******************]
[2024-04-24 10:11:21,897: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-24 10:11:21,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 10:11:21,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 10:11:21,904: INFO: common: created directory at: artifacts]
[2024-04-24 10:11:21,904: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-24 10:11:22,621: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-24 10:11:23,694: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-24 10:11:24,287: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-04-24 10:11:24,287: INFO: main: ******************]
[2024-04-24 10:11:24,287: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-24 10:11:24,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 10:11:24,296: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 10:11:24,296: INFO: common: created directory at: artifacts]
[2024-04-24 10:11:24,297: INFO: common: created directory at: artifacts\training]
[2024-04-24 10:32:20,206: INFO: main: >>>>>> stage Training completed <<<<<<]
[2024-04-24 10:32:20,207: INFO: main: ****************]
[2024-04-24 10:32:20,207: INFO: main: >>>>>> stage Evaluation started <<<<<<]
[2024-04-24 10:32:20,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 10:32:20,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 10:32:20,212: INFO: common: created directory at: artifacts]
[2024-04-24 10:38:08,912: INFO: common: json file saved at: scores.json]
[2024-04-24 10:38:08,913: INFO: common: json file saved at: scores.json]
[2024-04-24 10:38:14,546: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-24 10:38:17,997: INFO: builder_impl: Assets written to: C:\Users\khaled\AppData\Local\Temp\tmpq7xu_8ts\model\data\model\assets]
[2024-04-24 11:53:34,309: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-24 11:53:34,309: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-24 11:53:38,394: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-24 11:53:38,398: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 11:53:38,401: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 11:53:38,401: INFO: common: created directory at: artifacts]
[2024-04-24 11:53:38,402: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-24 12:06:39,790: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-24 12:06:39,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 12:06:39,798: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 12:06:39,800: INFO: common: created directory at: artifacts]
[2024-04-24 12:06:39,801: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-24 12:08:10,061: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-24 12:08:10,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 12:08:10,068: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 12:08:10,068: INFO: common: created directory at: artifacts]
[2024-04-24 12:08:10,069: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-24 12:13:51,262: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 12:14:15,604: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-24 15:02:34,335: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-24 15:02:34,339: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:02:34,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 15:02:34,343: INFO: common: created directory at: artifacts]
[2024-04-24 15:02:34,344: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-24 15:03:19,406: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-24 15:03:19,410: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:03:19,412: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-24 15:03:19,412: INFO: common: created directory at: artifacts]
[2024-04-24 15:03:19,413: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-24 15:09:25,503: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 15:09:47,774: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-26 12:28:37,162: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 12:28:37,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 12:28:37,169: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 12:28:37,170: INFO: common: created directory at: artifacts]
[2024-04-26 12:28:37,170: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 12:31:57,635: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 12:31:57,638: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 12:31:57,642: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 12:31:57,642: INFO: common: created directory at: artifacts]
[2024-04-26 12:31:57,643: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 12:38:57,128: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 12:39:18,191: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-26 12:44:15,206: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 12:44:15,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 12:44:15,213: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 12:44:15,214: INFO: common: created directory at: artifacts]
[2024-04-26 12:44:15,215: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 12:50:10,061: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 12:50:42,405: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-26 12:53:35,699: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 12:53:35,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 12:53:35,706: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 12:53:35,707: INFO: common: created directory at: artifacts]
[2024-04-26 12:53:35,708: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 12:59:52,209: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 13:00:17,202: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-26 13:03:39,281: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 13:03:39,286: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:03:39,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:03:39,294: INFO: common: created directory at: artifacts]
[2024-04-26 13:03:39,295: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 13:05:04,431: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:05:04,431: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:05:09,137: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 13:05:09,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:05:09,143: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:05:09,144: INFO: common: created directory at: artifacts]
[2024-04-26 13:05:09,144: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 13:11:36,187: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 13:12:09,991: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-26 13:12:09,992: INFO: main: ******************]
[2024-04-26 13:12:09,993: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-26 13:12:10,003: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:12:10,007: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:12:10,008: INFO: common: created directory at: artifacts]
[2024-04-26 13:12:10,010: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-26 13:12:11,502: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-26 13:12:13,647: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-26 13:12:14,799: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-04-26 13:12:14,800: INFO: main: ******************]
[2024-04-26 13:12:14,801: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-26 13:12:14,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:12:14,862: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:12:14,868: INFO: common: created directory at: artifacts]
[2024-04-26 13:12:14,870: INFO: common: created directory at: artifacts\training]
[2024-04-26 13:12:17,195: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 29, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-04-26 13:39:45,057: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:39:45,058: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:40:46,594: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:40:46,595: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:41:21,056: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:41:21,057: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:41:23,198: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.11:8080]
[2024-04-26 13:41:23,200: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-26 13:41:38,952: INFO: _internal: 127.0.0.1 - - [26/Apr/2024 13:41:38] "GET / HTTP/1.1" 200 -]
[2024-04-26 13:42:38,931: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("artifacts", "training", "model.h5"))
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\training\model.h5
[2024-04-26 13:42:38,944: INFO: _internal: 127.0.0.1 - - [26/Apr/2024 13:42:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-26 13:43:49,933: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:43:49,934: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:43:53,684: INFO: main: >>>>> stage Data Ingestion stage started <<<<<]
[2024-04-26 13:43:53,688: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:43:53,692: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:43:53,694: INFO: common: created directory at: artifacts]
[2024-04-26 13:43:53,785: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 13:49:39,559: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/16CDhrUVvI7epz0J0T2vHvo-onUgnZSPA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 13:50:04,513: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<<
nx=======x]
[2024-04-26 13:50:04,514: INFO: main: ******************]
[2024-04-26 13:50:04,514: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-26 13:50:04,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:50:04,528: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:50:04,528: INFO: common: created directory at: artifacts]
[2024-04-26 13:50:04,529: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-26 13:50:05,416: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-26 13:50:06,946: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-26 13:50:07,564: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x=========x]
[2024-04-26 13:50:07,569: INFO: main: ******************]
[2024-04-26 13:50:07,570: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-26 13:50:07,579: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:50:07,584: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:50:07,585: INFO: common: created directory at: artifacts]
[2024-04-26 13:50:07,649: INFO: common: created directory at: artifacts\training]
[2024-04-26 13:50:08,637: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 29, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-04-26 13:54:40,261: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:54:40,262: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:54:44,259: INFO: main: ******************]
[2024-04-26 13:54:44,260: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-26 13:54:44,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:54:44,266: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:54:44,267: INFO: common: created directory at: artifacts]
[2024-04-26 13:54:44,267: INFO: common: created directory at: artifacts\training]
[2024-04-26 13:54:45,062: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image']
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_training.main()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 29, in main
    training.train_valid_generator()
  File "D:\Courses\ML\MachineLearning\ML_Projects\Computer_Vision\Kidney_Disease_Classification_Project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\khaled\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney_ct_scan_image'
[2024-04-26 13:56:18,522: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-04-26 13:56:18,522: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-04-26 13:56:21,686: INFO: main: ******************]
[2024-04-26 13:56:21,687: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-26 13:56:21,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 13:56:21,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 13:56:21,696: INFO: common: created directory at: artifacts]
[2024-04-26 13:56:21,697: INFO: common: created directory at: artifacts\training]
[2024-04-26 14:18:35,237: INFO: main: >>>>>> stage Training completed <<<<<<]
[2024-04-26 14:18:35,237: INFO: main: ****************]
[2024-04-26 14:18:35,238: INFO: main: >>>>>> stage Evaluation started <<<<<<]
[2024-04-26 14:18:35,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-26 14:18:35,246: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 14:18:35,246: INFO: common: created directory at: artifacts]
[2024-04-26 14:18:58,752: INFO: _internal: 127.0.0.1 - - [26/Apr/2024 14:18:58] "GET / HTTP/1.1" 200 -]
[2024-04-26 14:19:51,473: INFO: _internal: 127.0.0.1 - - [26/Apr/2024 14:19:51] "POST /predict HTTP/1.1" 200 -]
[2024-04-26 14:25:21,288: INFO: common: json file saved at: scores.json]
[2024-04-26 14:25:21,290: INFO: common: json file saved at: scores.json]
[2024-04-26 14:25:21,290: INFO: main: >>>>>> stage Evaluation completed <<<<<<
 'nx========]
[2024-04-26 14:36:39,380: INFO: _internal: 127.0.0.1 - - [26/Apr/2024 14:36:39] "POST /predict HTTP/1.1" 200 -]
